#!/usr/bin/env python
import sys
import optparse
import radist

description = """The path specified in /R/notation/path.  The path can start
with /R or with /ix depending on required config file."""

def normal_run(node, command):
    return node.cluster_exec(command)

def parallel_run(node, command):
    return node.cluster_exec(command, parallel=True)

def parallel_prefix(node, command):
    for cur, line in radist.cluster_open(node, command):
        print cur.get('server'), ":", line

if __name__ == '__main__':
    usage = "%prog [options] node-path command"

    parser = optparse.OptionParser(usage=usage, description=description)
    parser.disable_interspersed_args()
    parser.set_defaults(cluster_run=normal_run, try_node=True)
    parser.add_option("--no_self",
        dest="try_node", action="store_false",
        help="do not try to run command on node itself")
    parser.add_option('-P',
        dest="cluster_run", action="store_const", const=parallel_run,
        help="run command in parallel")
    parser.add_option('-E',
        dest="cluster_run", action="store_const", const=parallel_prefix,
        help="run command in parallel and prefix each line with server name")
    radist.update_optparse(parser)
    options, args = parser.parse_args()
    if len(args) < 2:
        parser.error("need path and command")

    path = args.pop(0)
    p, path = path.split('/', 1)
    if p == '':
        p, path = path.split('/', 1)

    if p in ("ix", "IX"):
        root = radist.get_ix()
    elif p in ("r", "R"):
        root = radist.get_r()
    else:
        parser.error("unknown path root: '%s'" % p)

    node = root.get(path)
    if 'server' in node.get_attrs() and options.try_node:
        node.r_exec(' '.join(args))
    else:
        options.cluster_run(node, ' '.join(args))
