PORTNAME = radist
PORTVERSION = 0.2.3
PKGNAMEPREFIX = ${PYTHON_PKGNAMEPREFIX}
CATEGORIES = misc
MASTER_SITES = https://github.com/downloads/shigin/radist/
MAINTAINER = shigin@rambler-co.ru
COMMENT = Helper module to work with radist config
USE_PYTHON = 2.5+
USE_PYDISTUTILS = yes
.include <bsd.port.pre.mk>
PYTHON_CMD = ${PYTHONBASE}/bin/${PYTHON_VERSION}
PYDISTUTILS_INSTALLARGS = -c --prefix=${PREFIX}
.include <bsd.port.post.mk>
